### ISSUE TITLE
Not build with godot 3.1 stable

### ISSUE THREAD

**Issue by quangdat88** [sanja-sa/gddragonbones#26]
Plz help me fix error: fatal error C1083: Cannot open include file: 'version_generated.gen.h': No such file or directory.

**Comment by tomankirilov** [comment]
try adding this
env.Append( CPPPATH=['_full_path_to_/godot/core'] )
to the config.py file.

**Comment by tomankirilov** [comment]
UPDATE:
this "fix" does not work with gddragon bones.
After some testing I got more errors and in the end it fails to build.

**Comment by quangdat88** [comment]
Thank you.
I have been tried, build success but not work when run

**Comment by Ranoller** [comment]
My branch should work https://github.com/Ranoller/gddragonbones
There is still needed a decision about godot 2.1 3.0 3.1 branch, try to mantain or break compatibility:
https://github.com/sanja-sa/gddragonbones/issues/24
@sanja-sa

**Comment by blurymind** [comment]
@Ranoller why not make a pull request to this branch?

**Comment by tomankirilov** [comment]
@Ranoller it works just fine! Thank you!

**Comment by Ranoller** [comment]
> @Ranoller why not make a pull request to this branch?

Is possible to do that being not the propietary of the repository? I will investigate, but if you can branch the plugin in the actual state to a 3.0 branch y pull the changes to master branch... but the thing that i will not do is test retrocompatibility for godot 3 and 2 for every change in godot codebase because i will not use that branches and i don´t want compile that (not time)

**Comment by joaoluizn** [comment]
@Ranoller Please, dont let this code die, somehow try to pull request this version! Building nice for 3.1. Try to pull request creating a new branch.

**Comment by joaoluizn** [comment]
@Ranoller How to properly start an animation though scripting, it isn't working with the README functions.

**Comment by makilyang** [comment]
@Ranoller 3.1.1 build sucess buy can not run , 
object.cpp line 2034
instances.erase(p_object->get_instance_id());

**Comment by Ranoller** [comment]
I build master with my branch the last week and works... with 3.1 don´t kwown. Nobody is mantaining 2.1 and 3.1.... so please use master to work with this module. But I think that my branch start because akien change version_generated.h in godot so we can´t mantain compatibility with old versions because the #include method to test version changed.... i think.... don´t remember well....

**Comment by sanja-sa** [comment]
Please, choose stable version of Godot. It working with stable version correct.
